MODEL:
 modeler: matlab
 name: motoroil
 os: windows.7
 interface: modbus
 opc_parameters:
  actuators: noise_A=0.0, noise_B=0.0, noise_C=0.0, on_off=1.0, restart=0.0 #format actuators=> name=value, name=value, etc
  sensors: 75xi821bx, 75xi821by, 75xi822bx, 75xi822by, 75xi823bx, 75xi823by, 75xi824bx, 75xi824by, 75zi800ba, 75zi800bb, 75zi801ba, 75zi801bb, ST-7501_A, ST-7501_B, ST-7501_C, K-7502_A, K-7502_B, K-7502_C   #format sensors=> name, name, etc. 

MTU:
 name: mtu-hmi
 os: ubuntu
 hmi: scadabr
 set_alert: #optional, only for scadabr hmi. Type Supported: high_limit, low_limit, change, no_change
  type: high_limit
  variable: 75xi821bx > 89, 75xi822bx > 89

RTU: 
 name: 
 os: ubuntu
 input: position_X, position_Y, speed, station, start, nextWaypoints

PLC:
 name: plc1
 os: ubuntu
 input: 75xi821bx, restart
 output_slave: on_off, restart
 plc_code: motoroil.st #1 input, 1 output_slave, 1 output_master - TYPE=threshold control
    
    
GENERIC:
 name: 
 os: 

ROUTER_FIREWALL:
 name: router-gw
 os: ubuntu
 forwarding:
 - rules:
   - rule: src=internal_2 dst=internal_1
   - rule: src=internal_1 dst=internal_2


NETWORKS:
 name: internal_1; internal_2
 members: motoroil, plc1; mtu-hmi
 gateway: router-gw; router-gw
  

CONFIG:
 entry_point: mtu-hmi
 cyber_range_id: 50
 path: /home/ubuntu/virtualTestbed #path cyris directory
 ip_host: 192.168.1.65


SECURITY: # (optional) - Fix supported: ssh_root_deny
 vulnerability: ssh_root_deny
 target: router-gw

EXPORT_DATA: #TO KAFKA (optional)
 name: logstash
 ip_server: 192.168.1.188 #address ip kafka server
 read_topic: testbed  #enable reading from kafka to perform actions on vms
 public_to_kafka: #enable reading data from vms to kafka (separate element with "," ) - for enabling fill "topic"
  topic: stapp
  source_data: plc1; mtu-hmi   
  log_type: login; login #(element for same vm "," #element for different vm ";" )

#EXPORT_DATA: #TO KAFKA (optional)
# name: 
# ip_server: 192.168.1.188 #address ip kafka server
# read_topic: testbed #enable reading from kafka to perform actions on vms 
# source_data: mtu-hmi   #enable reading data from vms to kafka (separate element with "," )   
# log_type: login #(element for same vm "," #element for different vm ";" )
 



