/* Additional record code for controldc generated by the OpenModelica Compiler OpenModelica 1.14.1. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "controldc_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

